version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ministryhub_user
      POSTGRES_PASSWORD: ministryhub_password
      POSTGRES_DB: ministryhub
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
