export const API_PREFIX = '/api/v1';

export const ROLES = {
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
} as const;

export const MEMBERSHIP_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  TRANSFERRED: 'TRANSFERRED',
  DECEASED: 'DECEASED',
} as const;

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  EXCUSED: 'EXCUSED',
} as const;

export const ATTENDANCE_TYPE = {
  SUNDAY_WORSHIP: 'SUNDAY_WORSHIP',
  MIDWEEK_SERVICE: 'MIDWEEK_SERVICE',
  SPECIAL_EVENT: 'SPECIAL_EVENT',
  YOUTH_FELLOWSHIP: 'YOUTH_FELLOWSHIP',
  OUTREACH: 'OUTREACH',
  OTHER: 'OTHER',
} as const;

