import React from 'react';
import {
  IconPrinter,
  IconX,
  IconCalendar,
  IconCheck,
  IconX as IconCross,
  IconClock,
} from '@tabler/icons-react';
import { AttendanceRecordResponse } from '@ministryhub/types';
import './AttendancePdfModal.scss';

export interface AttendancePdfModalProps {
  isOpen: boolean;
  onClose: () => void;
  title?: string;
  subtitle?: string;
  dateRangeText: string;
  attendanceType: string;
  records: AttendanceRecordResponse[];
  generatedBy?: string;
}

export const AttendancePdfModal: React.FC<AttendancePdfModalProps> = ({
  isOpen,
  onClose,
  title = 'Attendance & Participation Report',
  subtitle = 'MinistryHub Attendance Records & Activity Documentation',
  dateRangeText,
  attendanceType,
  records,
  generatedBy = 'Church Administrator',
}) => {
  if (!isOpen) return null;

  const total = records.length;
  const present = records.filter((r) => r.status === 'PRESENT').length;
  const absent = records.filter((r) => r.status === 'ABSENT').length;
  const excused = records.filter((r) => r.status === 'EXCUSED').length;
  const percentage = total > 0 ? Math.round((present / total) * 100) : 0;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="pdf-modal-backdrop" onClick={onClose}>
      <div className="pdf-modal-container" onClick={(e) => e.stopPropagation()}>
        {/* Controls Toolbar (Hidden during print) */}
        <div className="pdf-modal-header no-print">
          <div className="pdf-header-info">
            <h2 className="pdf-modal-title">Attendance Report Preview</h2>
            <span className="pdf-modal-desc">
              Formatted for church documentation, administrative review, and printing.
            </span>
          </div>

          <div className="pdf-header-actions">
            <button className="btn btn-primary btn-print" onClick={handlePrint}>
              <IconPrinter size={18} stroke={2} />
              <span>Print / Save as PDF</span>
            </button>
            <button className="btn-close-modal" onClick={onClose} title="Close">
              <IconX size={20} stroke={2} />
            </button>
          </div>
        </div>

        {/* Printable Document Area */}
        <div className="printable-document">
          {/* MinistryHub Branding Header */}
          <div className="doc-header">
            <div className="doc-brand">
              <img src="/logo.png" alt="MinistryHub" className="doc-logo-img" />
            </div>


            <div className="doc-meta-badge">
              <span className="doc-badge-type">{attendanceType.replace(/_/g, ' ')}</span>
              <span className="doc-badge-date">
                <IconCalendar size={13} stroke={2} />
                {dateRangeText}
              </span>
            </div>
          </div>

          <div className="doc-divider" />

          {/* Title and Metadata */}
          <div className="doc-title-section">
            <h2 className="doc-main-title">{title}</h2>
            <p className="doc-main-subtitle">{subtitle}</p>

            <div className="doc-meta-grid">
              <div className="doc-meta-item">
                <span className="meta-label">Session / Scope:</span>
                <span className="meta-value">{attendanceType.replace(/_/g, ' ')}</span>
              </div>
              <div className="doc-meta-item">
                <span className="meta-label">Date / Range:</span>
                <span className="meta-value">{dateRangeText}</span>
              </div>
              <div className="doc-meta-item">
                <span className="meta-label">Generated By:</span>
                <span className="meta-value">{generatedBy}</span>
              </div>
              <div className="doc-meta-item">
                <span className="meta-label">Generated At:</span>
                <span className="meta-value">
                  {new Date().toLocaleDateString('en-US', {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit',
                  })}
                </span>
              </div>
            </div>
          </div>

          {/* Summary KPI Strip */}
          <div className="doc-kpi-strip">
            <div className="kpi-box">
              <span className="kpi-num">{total}</span>
              <span className="kpi-label">Total Roster</span>
            </div>
            <div className="kpi-box kpi-present">
              <span className="kpi-num">{present}</span>
              <span className="kpi-label">
                <IconCheck size={14} stroke={2.5} /> Present
              </span>
            </div>
            <div className="kpi-box kpi-absent">
              <span className="kpi-num">{absent}</span>
              <span className="kpi-label">
                <IconCross size={14} stroke={2.5} /> Absent
              </span>
            </div>
            <div className="kpi-box kpi-excused">
              <span className="kpi-num">{excused}</span>
              <span className="kpi-label">
                <IconClock size={14} stroke={2.5} /> Excused
              </span>
            </div>
            <div className="kpi-box kpi-rate">
              <span className="kpi-num">{percentage}%</span>
              <span className="kpi-label">Attendance Rate</span>
            </div>
          </div>

          {/* Member Attendance Table */}
          <div className="doc-table-container">
            <table className="doc-table">
              <thead>
                <tr>
                  <th style={{ width: '40px' }}>#</th>
                  <th>Member Name</th>
                  <th>Member ID</th>
                  <th>Contact</th>
                  <th>Attendance Date</th>
                  <th>Status</th>
                  <th>Notes / Remarks</th>
                </tr>
              </thead>
              <tbody>
                {records.length === 0 ? (
                  <tr>
                    <td colSpan={7} className="doc-empty-cell">
                      No attendance records found for this selection.
                    </td>
                  </tr>
                ) : (
                  records.map((rec, index) => {
                    const memberName = rec.member
                      ? `${rec.member.firstName} ${rec.member.lastName}`
                      : 'Unknown Member';
                    const memberCode = rec.member?.memberId || '—';
                    const phone = rec.member?.phoneNumber || '—';

                    return (
                      <tr key={rec.id || index}>
                        <td className="cell-num">{index + 1}</td>
                        <td className="cell-name">{memberName}</td>
                        <td className="cell-id">{memberCode}</td>
                        <td className="cell-contact">{phone}</td>
                        <td className="cell-date">
                          {new Date(
                            rec.attendanceDate.includes('T')
                              ? rec.attendanceDate
                              : rec.attendanceDate + 'T00:00:00Z',
                          ).toLocaleDateString('en-US', {
                            month: 'short',
                            day: 'numeric',
                            year: 'numeric',
                            timeZone: 'UTC',
                          })}
                        </td>
                        <td>
                          <span className={`doc-status-pill status-${rec.status.toLowerCase()}`}>
                            {rec.status}
                          </span>
                        </td>
                        <td className="cell-notes">{rec.notes || '—'}</td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>

          {/* Footer & Signature Section */}
          <div className="doc-footer">
            <div className="sig-block">
              <div className="sig-line" />
              <span className="sig-label">Recorded By (Ministry Leader)</span>
            </div>
            <div className="sig-block">
              <div className="sig-line" />
              <span className="sig-label">Verified & Approved (Head Pastor / Admin)</span>
            </div>
          </div>

          <div className="doc-bottom-note">
            <span>MinistryHub Church Management System • Confidential Church Record</span>
          </div>
        </div>
      </div>
    </div>
  );
};
